# Generated by Django 2.2.4 on 2019-08-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiMyserver', '0002_ks3models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ks3models',
            options={'verbose_name': 'ks3日存储量计量查询', 'verbose_name_plural': 'ks3日存储量计量查询'},
        ),
    ]
